// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.tree_sitter

public typealias TSStateId = UShort

public typealias TSSymbol = UShort

public typealias TSFieldId = UShort

public typealias ts_current_malloc = Pointer<(`$p0`: ULong) -> Pointer<Unit>>

public typealias ts_current_calloc = Pointer<(`$p0`: ULong, `$p1`: ULong) -> Pointer<Unit>>

public typealias ts_current_realloc = Pointer<(`$p0`: Pointer<Unit>, `$p1`: ULong) -> Pointer<Unit>>

public typealias ts_current_free = Pointer<(`$p0`: Pointer<Unit>) -> Unit>
