// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.tree_sitter

public typealias TSStateId = UShort

public typealias TSSymbol = UShort

public typealias TSFieldId = UShort

public typealias ts_current_malloc = Pointer<(size: ULong) -> Pointer<Unit>>

public typealias ts_current_calloc = Pointer<(count: ULong, size: ULong) -> Pointer<Unit>>

public typealias ts_current_realloc = Pointer<(ptr: Pointer<Unit>, size: ULong) -> Pointer<Unit>>

public typealias ts_current_free = Pointer<(ptr: Pointer<Unit>) -> Unit>
