// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.tree_sitter

public typealias TSStateId = UShort

public typealias TSSymbol = UShort

public typealias TSFieldId = UShort

public typealias DecodeFunction = Pointer<(
    string: Pointer<UByte>,
    length: UInt,
    code_point: Pointer<Int>,
) -> UInt>

public typealias ts_set_allocator_new_malloc = Pointer<(`$p0`: ULong) -> Pointer<Unit>>

public typealias ts_set_allocator_new_calloc = Pointer<(`$p0`: ULong, `$p1`: ULong) -> Pointer<Unit>>

public typealias ts_set_allocator_new_realloc = Pointer<(`$p0`: Pointer<Unit>, `$p1`: ULong) -> Pointer<Unit>>

public typealias ts_set_allocator_new_free = Pointer<(`$p0`: Pointer<Unit>) -> Unit>
