// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.tree_sitter

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

public enum class TSInputEncoding(
    public val `value`: Int,
) {
    UTF8(0),
    UTF16LE(1),
    UTF16BE(2),
    Custom(3),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            TSInputEncoding::class.java,
            "fromInt",
            MethodType.methodType(TSInputEncoding::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            TSInputEncoding::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): TSInputEncoding = when (value) {
            UTF8.value -> UTF8
            UTF16LE.value -> UTF16LE
            UTF16BE.value -> UTF16BE
            Custom.value -> Custom
            else -> error("enum not found")
        }
    }
}
