// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.tree_sitter

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

public enum class TSLogType(
    public val `value`: Int,
) {
    Parse(0),
    Lex(1),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            TSLogType::class.java,
            "fromInt",
            MethodType.methodType(TSLogType::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            TSLogType::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): TSLogType = when (value) {
            Parse.value -> Parse
            Lex.value -> Lex
            else -> error("enum not found")
        }
    }
}
