// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.tree_sitter

import java.lang.foreign.*
import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.VarHandle

@JvmInline
public value class TSParseOptions(
    public val `$mem`: MemorySegment,
) {
    public var payload: Pointer<Unit>
        get() = payloadHandle.get(this.`$mem`, 0L) as MemorySegment
        set(`value`) {
            payloadHandle.set(this.`$mem`, 0L, value)
        }

    public var progress_callback: Pointer<(state: Pointer<TSParseState>) -> Boolean>
        get() = progress_callbackHandle.get(this.`$mem`, 0L) as MemorySegment
        set(`value`) {
            progress_callbackHandle.set(this.`$mem`, 0L, value)
        }

    public constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(layout)
    })

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
            `$RuntimeHelper`.POINTER.withName("payload"),
            `$RuntimeHelper`.POINTER.withName("progress_callback"),
        ).withName("TSParseOptions")

        @JvmField
        public val payloadHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("payload"))

        @JvmField
        public val progress_callbackHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("progress_callback"))

        @JvmStatic
        public fun allocate(alloc: SegmentAllocator): TSParseOptions =
            TSParseOptions(alloc.allocate(layout))

        public fun interface progress_callback {
            @CFunctionInvoke
            public fun invoke(state: Pointer<TSParseState>): Boolean

            public fun allocate(arena: Arena): MemorySegment =
                Linker.nativeLinker().upcallStub(invokeHandle.bindTo(this), fd, arena)

            public companion object {
                @JvmStatic
                public val invokeHandle: MethodHandle =
                    MethodHandles.lookup().unreflect(progress_callback::class.java.methods.find {
                        it.getAnnotation(CFunctionInvoke::class.java) != null
                    }
                    )

                @JvmStatic
                public val fd: FunctionDescriptor = FunctionDescriptor.of(
                    ValueLayout.JAVA_BOOLEAN,
                    `$RuntimeHelper`.POINTER,
                )
            }
        }
    }
}
