// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.tree_sitter

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

public enum class TSQueryPredicateStepType(
    public val `value`: Int,
) {
    Done(0),
    Capture(1),
    String(2),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            TSQueryPredicateStepType::class.java,
            "fromInt",
            MethodType.methodType(TSQueryPredicateStepType::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            TSQueryPredicateStepType::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): TSQueryPredicateStepType = when (value) {
            Done.value -> Done
            Capture.value -> Capture
            String.value -> String
            else -> error("enum not found")
        }
    }
}
