// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.tree_sitter

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

public enum class TSSymbolType(
    public val `value`: Int,
) {
    Regular(0),
    Anonymous(1),
    Auxiliary(2),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            TSSymbolType::class.java,
            "fromInt",
            MethodType.methodType(TSSymbolType::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            TSSymbolType::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): TSSymbolType = when (value) {
            Regular.value -> Regular
            Anonymous.value -> Anonymous
            Auxiliary.value -> Auxiliary
            else -> error("enum not found")
        }
    }
}
