// this file is auto generated by endoqa kotlin ffi, modify it with caution
package tree_sitter.c

import java.lang.foreign.*
import kotlin.jvm.optionals.getOrElse

public typealias Pointer<T> = MemorySegment

public typealias NativeArray<T> = MemorySegment

public typealias Void = Unit

public typealias NativeMemory<T> = MemorySegment

public object `$RuntimeHelper` {
    @JvmStatic
    public val linker: Linker = Linker.nativeLinker()

    @JvmStatic
    public val loaderLookup: SymbolLookup = SymbolLookup.loaderLookup()

    @JvmStatic
    public val POINTER: AddressLayout =
        ValueLayout.ADDRESS.withTargetLayout(
            MemoryLayout.sequenceLayout(
                Long.MAX_VALUE,
                ValueLayout.JAVA_BYTE
            )
        )

    @JvmStatic
    public val symbolLookup: SymbolLookup = SymbolLookup { name ->
        val inLoader = loaderLookup.find(name)
        if (inLoader.isEmpty) {
            loaderLookup.find(name)
        } else {
            inLoader
        }
    }

    @JvmStatic
    public fun findSymbol(symbol: String): MemorySegment = symbolLookup.find(symbol).getOrElse {
        error("unable to find symbol $symbol")
    }
}
