// this file is auto generated by endoqa kotlin ffi, modify it with caution
package tree_sitter.c

public typealias int64_t = Long

public typealias uint16_t = UShort

public typealias uint32_t = UInt

public typealias uint64_t = ULong

public typealias TSStateId = uint16_t

public typealias TSSymbol = uint16_t

public typealias TSFieldId = uint16_t
