// this file is auto generated by endoqa kotlin ffi, modify it with caution
package tree_sitter.c

public enum class TSInputEncoding(
    public val `value`: Int,
) {
    UTF8(0x00000000),
    UTF16(0x00000001),
    ;

    public companion object {
        public fun fromInt(`value`: Int): TSInputEncoding = when (value) {
            0x00000000 -> UTF8
            0x00000001 -> UTF16
            else -> error("enum not found")
        }
    }
}
