// this file is auto generated by endoqa kotlin ffi, modify it with caution
package tree_sitter.c

public enum class TSQueryError(
    public val `value`: Int,
) {
    None(0x00000000),
    Syntax(0x00000001),
    NodeType(0x00000002),
    Field(0x00000003),
    Capture(0x00000004),
    Structure(0x00000005),
    Language(0x00000006),
    ;

    public companion object {
        public fun fromInt(`value`: Int): TSQueryError = when (value) {
            0x00000000 -> None
            0x00000001 -> Syntax
            0x00000002 -> NodeType
            0x00000003 -> Field
            0x00000004 -> Capture
            0x00000005 -> Structure
            0x00000006 -> Language
            else -> error("enum not found")
        }
    }
}
