// this file is auto generated by endoqa kotlin ffi, modify it with caution
package tree_sitter.c

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

public enum class TSQueryPredicateStepType(
    public val `value`: Int,
) {
    TSQueryPredicateStepTypeDone(0x00000000),
    TSQueryPredicateStepTypeCapture(0x00000001),
    TSQueryPredicateStepTypeString(0x00000002),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            TSQueryPredicateStepType::class.java,
            "fromInt",
            MethodType.methodType(TSQueryPredicateStepType::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            TSQueryPredicateStepType::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): TSQueryPredicateStepType = when (value) {
            0x00000000 -> TSQueryPredicateStepTypeDone
            0x00000001 -> TSQueryPredicateStepTypeCapture
            0x00000002 -> TSQueryPredicateStepTypeString
            else -> error("enum not found")
        }
    }
}
