// this file is auto generated by endoqa kotlin ffi, modify it with caution
package tree_sitter.c

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

public enum class TSQuantifier(
    public val `value`: Int,
) {
    TSQuantifierZero(0x00000000),
    TSQuantifierZeroOrOne(0x00000001),
    TSQuantifierZeroOrMore(0x00000002),
    TSQuantifierOne(0x00000003),
    TSQuantifierOneOrMore(0x00000004),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            TSQuantifier::class.java,
            "fromInt",
            MethodType.methodType(TSQuantifier::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            TSQuantifier::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): TSQuantifier = when (value) {
            0x00000000 -> TSQuantifierZero
            0x00000001 -> TSQuantifierZeroOrOne
            0x00000002 -> TSQuantifierZeroOrMore
            0x00000003 -> TSQuantifierOne
            0x00000004 -> TSQuantifierOneOrMore
            else -> error("enum not found")
        }
    }
}
