// this file is auto generated by endoqa kotlin ffi, modify it with caution
package tree_sitter.c

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

public enum class TSSymbolType(
    public val `value`: Int,
) {
    TSSymbolTypeRegular(0x00000000),
    TSSymbolTypeAnonymous(0x00000001),
    TSSymbolTypeAuxiliary(0x00000002),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            TSSymbolType::class.java,
            "fromInt",
            MethodType.methodType(TSSymbolType::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            TSSymbolType::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): TSSymbolType = when (value) {
            0x00000000 -> TSSymbolTypeRegular
            0x00000001 -> TSSymbolTypeAnonymous
            0x00000002 -> TSSymbolTypeAuxiliary
            else -> error("enum not found")
        }
    }
}
