// this file is auto generated by endoqa kotlin ffi, modify it with caution
package tree_sitter.c

import java.lang.foreign.MemoryLayout
import java.lang.foreign.MemorySegment
import java.lang.foreign.StructLayout
import java.lang.foreign.ValueLayout
import java.lang.invoke.MethodHandle
import java.lang.invoke.VarHandle

@JvmInline
public value class TSTreeCursor(
    public val `$mem`: MemorySegment,
) {
    public var tree: Pointer<Unit>
        get() = TSTreeCursor.treeHandle.get(this.`$mem`, 0L) as MemorySegment
        set(`value`) {
            TSTreeCursor.treeHandle.set(this.`$mem`, 0L, value)
        }

    public var id: Pointer<Unit>
        get() = TSTreeCursor.idHandle.get(this.`$mem`, 0L) as MemorySegment
        set(`value`) {
            TSTreeCursor.idHandle.set(this.`$mem`, 0L, value)
        }

    public val context: NativeArray<uint32_t>
        get() = TSTreeCursor.contextHandle.invokeExact(this.`$mem`) as MemorySegment

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
            `$RuntimeHelper`.POINTER.withName("tree"),
            `$RuntimeHelper`.POINTER.withName("id"),
            MemoryLayout.sequenceLayout(3L, ValueLayout.JAVA_INT).withName("context"),
            java.lang.foreign.MemoryLayout.paddingLayout(4),
        ).withName("TSTreeCursor")

        @JvmField
        public val treeHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("tree"))

        @JvmField
        public val idHandle: VarHandle = layout.varHandle(MemoryLayout.PathElement.groupElement("id"))

        @JvmField
        public val contextHandle: MethodHandle =
            layout.sliceHandle(MemoryLayout.PathElement.groupElement("context"))
    }
}
