// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.tree_sitter.proc

import lib.tree_sitter.`$RuntimeHelper`
import lib.tree_sitter.Pointer
import java.lang.foreign.*
import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles

public fun interface ts_current_realloc {
    public fun invoke(ptr: Pointer<Unit>, size: ULong): Pointer<Unit>

    public fun allocate(arena: Arena): MemorySegment =
        Linker.nativeLinker().upcallStub(invokeHandle.bindTo(this), fd, arena)

    public companion object {
        @JvmStatic
        public val invokeHandle: MethodHandle =
            MethodHandles.lookup().unreflect(ts_current_realloc::class.java.methods.find {
                it.name == "invoke"
            }
            )

        @JvmStatic
        public val fd: FunctionDescriptor = FunctionDescriptor.of(
            `$RuntimeHelper`.POINTER,
            `$RuntimeHelper`.POINTER,
            ValueLayout.JAVA_LONG,
        )
    }
}
