// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.tree_sitter.proc

import lib.tree_sitter.`$RuntimeHelper`
import lib.tree_sitter.CFunctionInvoke
import lib.tree_sitter.Pointer
import java.lang.foreign.*
import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles

public fun interface ts_set_allocator_new_calloc {
    @CFunctionInvoke
    public fun invoke(`$p0`: ULong, `$p1`: ULong): Pointer<Unit>

    public fun allocate(arena: Arena): MemorySegment =
        Linker.nativeLinker().upcallStub(invokeHandle.bindTo(this), fd, arena)

    public companion object {
        @JvmStatic
        public val invokeHandle: MethodHandle =
            MethodHandles.lookup().unreflect(ts_set_allocator_new_calloc::class.java.methods.find {
                it.getAnnotation(CFunctionInvoke::class.java) != null
            }
            )

        @JvmStatic
        public val fd: FunctionDescriptor = FunctionDescriptor.of(
            `$RuntimeHelper`.POINTER,
            ValueLayout.JAVA_LONG,
            ValueLayout.JAVA_LONG,
        )
    }
}
