// this file is auto generated by endoqa kotlin ffi, modify it with caution
package tree_sitter.c

import java.lang.foreign.MemoryLayout
import java.lang.foreign.MemorySegment
import java.lang.foreign.StructLayout

@JvmInline
public value class TSLanguage(
    public val `$mem`: MemorySegment,
) {
    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
        ).withName("TSLanguage")
    }
}
