// this file is auto generated by endoqa kotlin ffi, modify it with caution
package tree_sitter.c

public enum class TSQuantifier(
    public val `value`: Int,
) {
    Zero(0x00000000),
    ZeroOrOne(0x00000001),
    ZeroOrMore(0x00000002),
    One(0x00000003),
    OneOrMore(0x00000004),
    ;

    public companion object {
        public fun fromInt(`value`: Int): TSQuantifier = when (value) {
            0x00000000 -> Zero
            0x00000001 -> ZeroOrOne
            0x00000002 -> ZeroOrMore
            0x00000003 -> One
            0x00000004 -> OneOrMore
            else -> error("enum not found")
        }
    }
}
