// this file is auto generated by endoqa kotlin ffi, modify it with caution
package tree_sitter.c

public enum class TSSymbolType(
    public val `value`: Int,
) {
    Regular(0x00000000),
    Anonymous(0x00000001),
    Auxiliary(0x00000002),
    ;

    public companion object {
        public fun fromInt(`value`: Int): TSSymbolType = when (value) {
            0x00000000 -> Regular
            0x00000001 -> Anonymous
            0x00000002 -> Auxiliary
            else -> error("enum not found")
        }
    }
}
