// this file is auto generated by endoqa kotlin ffi, modify it with caution
package tree_sitter

import java.lang.foreign.MemoryLayout
import java.lang.foreign.MemorySegment
import java.lang.foreign.StructLayout
import java.lang.foreign.ValueLayout
import java.lang.invoke.VarHandle
import kotlin.Byte
import kotlin.Int
import kotlin.Unit
import kotlin.jvm.JvmField
import kotlin.jvm.JvmInline

@JvmInline
public value class TSInput(
    public val `$mem`: MemorySegment,
) {
    public var payload: Pointer<Unit>
        get() = TSInput.payloadHandle.get(this.`$mem`, 0L) as MemorySegment
        set(`value`) {
            TSInput.payloadHandle.set(this.`$mem`, 0L, value)
        }

    public var read: Pointer<(
        payload: Pointer<Unit>,
        byte_index: uint32_t,
        position: TSPoint,
        bytes_read: Pointer<uint32_t>,
    ) -> Pointer<Byte>>
        get() = TSInput.readHandle.get(this.`$mem`, 0L) as MemorySegment
        set(`value`) {
            TSInput.readHandle.set(this.`$mem`, 0L, value)
        }

    public var encoding: TSInputEncoding
        get() = TSInputEncoding.fromInt(TSInput.encodingHandle.get(this.`$mem`, 0L) as Int)
        set(`value`) {
            TSInput.encodingHandle.set(this.`$mem`, 0L, value.value)
        }

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
            `$RuntimeHelper`.POINTER.withName("payload"),
            `$RuntimeHelper`.POINTER.withName("read"),
            ValueLayout.JAVA_INT.withName("encoding"),
            java.lang.foreign.MemoryLayout.paddingLayout(4),
        ).withName("TSInput")

        @JvmField
        public val payloadHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("payload"))

        @JvmField
        public val readHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("read"))

        @JvmField
        public val encodingHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("encoding"))
    }
}
