// this file is auto generated by endoqa kotlin ffi, modify it with caution
package tree_sitter

import java.lang.foreign.MemoryLayout
import java.lang.foreign.MemorySegment
import java.lang.foreign.StructLayout
import java.lang.foreign.ValueLayout
import java.lang.invoke.VarHandle
import kotlin.Unit
import kotlin.jvm.JvmField
import kotlin.jvm.JvmInline

@JvmInline
public value class TSNode(
    public val `$mem`: MemorySegment,
) {
    public var context: NativeArray<uint32_t>
        get() = TSNode.contextHandle.get(this.`$mem`) as MemorySegment
        set(`value`) {
            TSNode.contextHandle.set(this.`$mem`, value)
        }

    public var id: Pointer<Unit>
        get() = TSNode.idHandle.get(this.`$mem`) as MemorySegment
        set(`value`) {
            TSNode.idHandle.set(this.`$mem`, value)
        }

    public var tree: Pointer<TSTree>
        get() = TSNode.treeHandle.get(this.`$mem`) as MemorySegment
        set(`value`) {
            TSNode.treeHandle.set(this.`$mem`, value)
        }

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
            MemoryLayout.sequenceLayout(4L, ValueLayout.JAVA_INT).withName("context"),
            `$RuntimeHelper`.POINTER.withName("id"),
            `$RuntimeHelper`.POINTER.withName("tree"),
        ).withName("TSNode")

        @JvmField
        public val contextHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("context"))

        @JvmField
        public val idHandle: VarHandle = layout.varHandle(MemoryLayout.PathElement.groupElement("id"))

        @JvmField
        public val treeHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("tree"))
    }
}
