// this file is auto generated by endoqa kotlin ffi, modify it with caution
package tree_sitter

import java.lang.foreign.MemoryLayout
import java.lang.foreign.MemorySegment
import java.lang.foreign.StructLayout
import java.lang.foreign.ValueLayout
import java.lang.invoke.VarHandle
import kotlin.Int
import kotlin.jvm.JvmField
import kotlin.jvm.JvmInline

@JvmInline
public value class TSPoint(
    public val `$mem`: MemorySegment,
) {
    public var row: uint32_t
        get() = (TSPoint.rowHandle.get(this.`$mem`) as Int).toUInt()
        set(`value`) {
            TSPoint.rowHandle.set(this.`$mem`, value.toInt())
        }

    public var column: uint32_t
        get() = (TSPoint.columnHandle.get(this.`$mem`) as Int).toUInt()
        set(`value`) {
            TSPoint.columnHandle.set(this.`$mem`, value.toInt())
        }

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
            ValueLayout.JAVA_INT.withName("row"),
            ValueLayout.JAVA_INT.withName("column"),
        ).withName("TSPoint")

        @JvmField
        public val rowHandle: VarHandle = layout.varHandle(MemoryLayout.PathElement.groupElement("row"))

        @JvmField
        public val columnHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("column"))
    }
}
