// this file is auto generated by endoqa kotlin ffi, modify it with caution
package tree_sitter

import java.lang.foreign.MemoryLayout
import java.lang.foreign.MemorySegment
import java.lang.foreign.StructLayout
import java.lang.foreign.ValueLayout
import java.lang.invoke.VarHandle
import kotlin.Int
import kotlin.Short
import kotlin.jvm.JvmField
import kotlin.jvm.JvmInline

@JvmInline
public value class TSQueryMatch(
    public val `$mem`: MemorySegment,
) {
    public var id: uint32_t
        get() = (TSQueryMatch.idHandle.get(this.`$mem`) as Int).toUInt()
        set(`value`) {
            TSQueryMatch.idHandle.set(this.`$mem`, value.toInt())
        }

    public var pattern_index: uint16_t
        get() = (TSQueryMatch.pattern_indexHandle.get(this.`$mem`) as Short).toUShort()
        set(`value`) {
            TSQueryMatch.pattern_indexHandle.set(this.`$mem`, value.toShort())
        }

    public var capture_count: uint16_t
        get() = (TSQueryMatch.capture_countHandle.get(this.`$mem`) as Short).toUShort()
        set(`value`) {
            TSQueryMatch.capture_countHandle.set(this.`$mem`, value.toShort())
        }

    public var captures: Pointer<TSQueryCapture>
        get() = TSQueryMatch.capturesHandle.get(this.`$mem`) as MemorySegment
        set(`value`) {
            TSQueryMatch.capturesHandle.set(this.`$mem`, value)
        }

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
            ValueLayout.JAVA_INT.withName("id"),
            ValueLayout.JAVA_SHORT.withName("pattern_index"),
            ValueLayout.JAVA_SHORT.withName("capture_count"),
            `$RuntimeHelper`.POINTER.withName("captures"),
        ).withName("TSQueryMatch")

        @JvmField
        public val idHandle: VarHandle = layout.varHandle(MemoryLayout.PathElement.groupElement("id"))

        @JvmField
        public val pattern_indexHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("pattern_index"))

        @JvmField
        public val capture_countHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("capture_count"))

        @JvmField
        public val capturesHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("captures"))
    }
}
