// this file is auto generated by endoqa kotlin ffi, modify it with caution
package tree_sitter

import java.lang.foreign.MemoryLayout
import java.lang.foreign.MemorySegment
import java.lang.foreign.StructLayout
import java.lang.foreign.ValueLayout
import java.lang.invoke.VarHandle
import kotlin.Int
import kotlin.UInt
import kotlin.jvm.JvmField
import kotlin.jvm.JvmInline

@JvmInline
public value class TSQueryPredicateStep(
    public val `$mem`: MemorySegment,
) {
    public var type: TSQueryPredicateStepType
        get() = TSQueryPredicateStepType.fromInt(
            TSQueryPredicateStep.typeHandle.get(this.`$mem`) as
                Int
        )
        set(`value`) {
            TSQueryPredicateStep.typeHandle.set(this.`$mem`, value.value)
        }

    public var value_id: uint32_t
        get() = (TSQueryPredicateStep.value_idHandle.get(this.`$mem`) as UInt).toUInt()
        set(`value`) {
            TSQueryPredicateStep.value_idHandle.set(this.`$mem`, value.toInt())
        }

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
            ValueLayout.JAVA_INT.withName("type"),
            ValueLayout.JAVA_INT.withName("value_id"),
        ).withName("TSQueryPredicateStep")

        @JvmField
        public val typeHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("type"))

        @JvmField
        public val value_idHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("value_id"))
    }
}
