// this file is auto generated by endoqa kotlin ffi, modify it with caution
package tree_sitter

import java.lang.foreign.MemoryLayout
import java.lang.foreign.MemorySegment
import java.lang.foreign.StructLayout
import java.lang.foreign.ValueLayout
import java.lang.invoke.VarHandle
import kotlin.Unit
import kotlin.jvm.JvmField
import kotlin.jvm.JvmInline

@JvmInline
public value class TSTreeCursor(
    public val `$mem`: MemorySegment,
) {
    public var tree: Pointer<Unit>
        get() = TSTreeCursor.treeHandle.get(this.`$mem`) as MemorySegment
        set(`value`) {
            TSTreeCursor.treeHandle.set(this.`$mem`, value)
        }

    public var id: Pointer<Unit>
        get() = TSTreeCursor.idHandle.get(this.`$mem`) as MemorySegment
        set(`value`) {
            TSTreeCursor.idHandle.set(this.`$mem`, value)
        }

    public var context: NativeArray<uint32_t>
        get() = TSTreeCursor.contextHandle.get(this.`$mem`) as MemorySegment
        set(`value`) {
            TSTreeCursor.contextHandle.set(this.`$mem`, value)
        }

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
            `$RuntimeHelper`.POINTER.withName("tree"),
            `$RuntimeHelper`.POINTER.withName("id"),
            MemoryLayout.sequenceLayout(3L, ValueLayout.JAVA_INT).withName("context"),
            java.lang.foreign.MemoryLayout.paddingLayout(4),
        ).withName("TSTreeCursor")

        @JvmField
        public val treeHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("tree"))

        @JvmField
        public val idHandle: VarHandle = layout.varHandle(MemoryLayout.PathElement.groupElement("id"))

        @JvmField
        public val contextHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("context"))
    }
}
