// this file is auto generated by endoqa kotlin ffi, modify it with caution
package tree_sitter

import kotlin.Int
import tree_sitter.TSWasmErrorKind.Allocate
import tree_sitter.TSWasmErrorKind.Compile
import tree_sitter.TSWasmErrorKind.Instantiate
import tree_sitter.TSWasmErrorKind.None
import tree_sitter.TSWasmErrorKind.Parse

public enum class TSWasmErrorKind(
    public val `value`: Int,
) {
    None(0x00000000),
    Parse(0x00000001),
    Compile(0x00000002),
    Instantiate(0x00000003),
    Allocate(0x00000004),
    ;

    public companion object {
        public fun fromInt(`value`: Int): TSWasmErrorKind = when (value) {
            0x00000000 -> None
            0x00000001 -> Parse
            0x00000002 -> Compile
            0x00000003 -> Instantiate
            0x00000004 -> Allocate
            else -> error("enum not found")
        }
    }
}
