// this file is auto generated by endoqa kotlin ffi, modify it with caution
package tree_sitter

import java.lang.foreign.MemoryLayout
import java.lang.foreign.MemorySegment
import java.lang.foreign.StructLayout
import kotlin.jvm.JvmInline

@JvmInline
public value class wasm_engine_t(
    public val `$mem`: MemorySegment,
) {
    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
        ).withName("wasm_engine_t")
    }
}
