// this file is auto generated by endoqa kotlin ffi, modify it with caution
package tree_sitter

import kotlin.Int
import tree_sitter.TSLogType.Lex
import tree_sitter.TSLogType.Parse

public enum class TSLogType(
    public val `value`: Int,
) {
    Parse(0x00000000),
    Lex(0x00000001),
    ;

    public companion object {
        public fun fromInt(`value`: Int): TSLogType = when (value) {
            0x00000000 -> Parse
            0x00000001 -> Lex
            else -> error("enum not found")
        }
    }
}
